# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# For setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# Check the window size after each command and, if necessary
# update the values of LINES and COLUMNS
shopt -s checkwinsize

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Set color
[ -x /usr/bin/tput ] && tput setaf 1 >/dev/null && color_prompt=yes
# We have color support; assume it's compliant with Ecma-48
# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
# a case would tend to support setf rather than setaf.)

if [ "$color_prompt" = yes ]
then
	PS1='\[\033[COLOR1m\]\u@\h\[\033[0m\]:\[\033[COLOR2m\]\w\[\033[0m\]\$ '
else
	PS1='\u@\h:\w\$ '
fi
unset color_prompt

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]
then
	if [ -r $HOME/.dircolors ]
	then
		eval "$(dircolors -b $HOME/.dircolors)"
	else
		eval "$(dircolors -b)"
	fi
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
	alias fgrep='fgrep --color=auto'
	alias egrep='egrep --color=auto'
fi

# Set PATH so it includes user's private bin if it exists
[ -d "$HOME/.bin" ] && [[ "$PATH" != *"$HOME/.bin"* ]] && PATH="$HOME/.bin:$PATH"

# Private configuration
[ -f ~/.bash_priv ] && . ~/.bash_priv

# Alias definitions
[ -f ~/.bash_aliases ] && . ~/.bash_aliases

# Enable programmable completion features
[ -f /etc/bash_completion ] && ! shopt -oq posix && . /etc/bash_completion
